# Generated by Django 5.1.7 on 2025-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='updates_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
