# Generated by Django 5.1.7 on 2025-04-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='materials',
            field=models.FileField(blank=True, help_text='Upload presentation materials (limit: 50MB)', null=True, upload_to='speaker_materials/'),
        ),
    ]
