# Generated by Django 5.1.7 on 2025-05-12 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_capacity_event_enable_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='materials',
            field=models.FileField(blank=True, help_text='Upload presentation materials (limit: 50MB)', null=True, upload_to='speaker_materials/'),
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('event_speaker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(blank=True, help_text="Topic or title of the speaker's presentation", max_length=255)),
                ('presentation_time', models.DateTimeField(blank=True, help_text='Scheduled time for the presentation', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the presentation in minutes')),
                ('is_keynote', models.BooleanField(default=False, help_text='Whether this is a keynote presentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='events.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_events', to='events.speaker')),
            ],
            options={
                'ordering': ['presentation_time', 'created_at'],
                'unique_together': {('event', 'speaker')},
            },
        ),
    ]
