# Generated by Django 5.1.7 on 2025-05-24 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20250524_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, help_text="e.g., '1-50 employees', '500+ employees'", max_length=50)),
                ('primary_contact_name', models.CharField(max_length=100)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=20)),
                ('primary_contact_title', models.CharField(blank=True, max_length=100)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=100)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=20)),
                ('secondary_contact_title', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sponsor_banners/')),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text='Social media links')),
                ('marketing_materials', models.FileField(blank=True, help_text='Marketing materials, brochures, etc.', null=True, upload_to='sponsor_materials/')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the sponsor')),
                ('special_requirements', models.TextField(blank=True, help_text='Special requirements or requests')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor Profile',
                'verbose_name_plural': 'Sponsor Profiles',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('tier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tiers (lower numbers first)')),
                ('color_code', models.CharField(default='#000000', help_text='Hex color code for the tier', max_length=7)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('logo_placement', models.CharField(blank=True, help_text='Where the sponsor logo will be placed', max_length=100)),
                ('booth_space', models.CharField(blank=True, help_text='Booth space allocation', max_length=100)),
                ('speaking_opportunities', models.BooleanField(default=False)),
                ('networking_access', models.BooleanField(default=False)),
                ('marketing_materials', models.BooleanField(default=False)),
                ('social_media_mentions', models.PositiveIntegerField(default=0, help_text='Number of social media mentions')),
                ('email_mentions', models.PositiveIntegerField(default=0, help_text='Number of email newsletter mentions')),
                ('additional_benefits', models.JSONField(blank=True, default=list, help_text='List of additional benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor Tier',
                'verbose_name_plural': 'Sponsor Tiers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['tier__display_order', 'sponsor_profile__company_name'], 'verbose_name': 'Event Sponsor', 'verbose_name_plural': 'Event Sponsors'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='custom_benefits',
            field=models.JSONField(blank=True, default=list, help_text='Custom benefits for this sponsorship'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier_legacy',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.event'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='events.sponsorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together={('event', 'sponsor_profile')},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.sponsortier'),
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='name',
        ),
    ]
