# Generated by Django 5.1.7 on 2025-06-06 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_sponsorprofile_sponsortier_alter_sponsor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('booth_visit', 'Booth Visit'), ('material_download', 'Material Download'), ('contact_request', 'Contact Request'), ('meeting_scheduled', 'Meeting Scheduled'), ('demo_attended', 'Demo Attended'), ('survey_completed', 'Survey Completed'), ('other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('engagement_score', models.IntegerField(default=1)),
                ('follow_up_status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('converted', 'Converted'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_interactions', to='events.registration')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='events.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor Interaction',
                'verbose_name_plural': 'Sponsor Interactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SponsorMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sponsor_materials/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_materials', to='events.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='events.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor Material',
                'verbose_name_plural': 'Sponsor Materials',
                'ordering': ['-upload_date'],
            },
        ),
    ]
