# Generated by Django 5.1.7 on 2025-06-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_sponsor_name'),
        ('events', '0018_add_sponsor_name'),
        ('events', '0024_notification_is_read'),
    ]

    operations = [
    ]
