# Generated by Django 5.1.7 on 2025-06-06 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_merge_20250606_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_tech', models.BooleanField(default=True, help_text='Whether this is a technology-related tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Tag',
                'verbose_name_plural': 'Event Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventtag'),
        ),
    ]
