# Generated by Django 5.1.7 on 2025-06-07 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventtag_event_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon_class',
            field=models.CharField(default='fas fa-bell', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_reminder', 'Event Reminder'), ('registration', 'Registration Update'), ('event_update', 'Event Update'), ('feedback', 'Feedback Request'), ('system', 'System Notification')], max_length=20),
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='event',
            new_name='related_event',
        ),
    ] 