# Generated by Django 5.1.7 on 2025-06-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_add_it_event_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-feedback_id']},
        ),
    ]
