# Generated by Django 5.1.7 on 2025-06-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_feedback_options_feedback_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
