# Generated by Django 5.1.7 on 2025-04-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_speaker_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='materials',
        ),
        migrations.AlterField(
            model_name='event',
            name='rulebook',
            field=models.FileField(blank=True, null=True, upload_to='event_rulebooks/'),
        ),
    ]
