# Generated by Django 5.1.7 on 2025-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_blogcategory_contactinformation_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of attendees allowed'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_registration',
            field=models.BooleanField(default=True, help_text='Allow users to register for this event'),
        ),
    ]
