# Generated by Django 5.1.7 on 2025-05-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_registration_agreed_to_terms_registration_checked_in_and_more'),
    ]

    operations = [
    ]
