# Generated by Django 5.1.7 on 2025-05-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_sponsorprofile_sponsortier_alter_sponsor_options_and_more'),
    ]

    operations = [
    ]
