# Generated by Django 5.1.7 on 2025-06-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_sponsorinteraction_sponsormaterial'),
    ]

    operations = [
    ]
