# Generated by Django 5.1.7 on 2025-06-07 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_update_notification_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='color',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
