from django.urls import path
from . import views
from . import admin_views

urlpatterns = [
    # Speaker dashboard pages
    path('speaker/schedule/', views.speaker_schedule, name='speaker_schedule'),
    path('speaker/materials/', views.speaker_materials, name='speaker_materials'),
    path('speaker/guidelines/', views.speaker_guidelines, name='speaker_guidelines'),
    path('speaker/guidelines/pdf/', views.speaker_guidelines_pdf, name='speaker_guidelines_pdf'),
    path('speaker/feedback/', views.speaker_feedback, name='speaker_feedback'),
    path('test-qr-code/', views.test_qr_code, name='test_qr_code'),
    path('dashboard/organizer/', views.organizer_dashboard, name='organizer_dashboard'),
    path('dashboard/speaker/', views.speaker_dashboard, name='speaker_dashboard'),
    path('dashboard/attendee/', views.attendee_dashboard, name='attendee_dashboard'),
    path('dashboard/attendee/recent-events/', views.recent_events, name='recent_events'),
    path('dashboard/attendee/my-reviews/', views.my_reviews, name='my_reviews'),
    path('dashboard/attendee/my-tickets/', views.my_tickets, name='my_tickets'),
    path('dashboard/attendee/profile/', views.attendee_profile, name='attendee_profile'),
    path('notifications/', views.all_notifications, name='all_notifications'),
    path('notifications/list/', views.get_notifications, name='get_notifications'),
    path('notifications/mark-read/<uuid:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/preferences/', views.notification_preferences, name='notification_preferences'),
    path('admin/create-event-reminders/', views.create_event_reminders, name='create_event_reminders'),

    # URLs for organizer actions
    path('events/my/', views.my_events, name='my_events'),
    path('events/create/', views.create_event, name='create_event'),
    path('events/<uuid:event_id>/edit/', views.edit_event, name='edit_event'),
    path('speakers/manage/', views.manage_speakers, name='manage_speakers'),
    path('sponsors/manage/', views.manage_sponsors, name='manage_sponsors'),
    path('sponsors/create-default-tiers/', views.create_default_sponsor_tiers, name='create_default_sponsor_tiers'),
    path('sponsors/setup-enhanced/', views.setup_enhanced_sponsors_view, name='setup_enhanced_sponsors'),
    path('reports/', views.reports, name='reports'),
    path('registrations/all/', views.all_registrations, name='all_registrations'),
    path('registrations/export/', views.export_all_registrations, name='export_all_registrations'),
    path('feedback/all/', views.all_feedback, name='all_feedback'),
    path('feedback/pdf/', views.feedback_pdf, name='feedback_pdf'),
    path('events/<uuid:event_id>/', views.event_detail, name='event_detail'),
    path('events/<uuid:event_id>/pdf/', views.event_pdf, name='event_pdf'),
    path('events/<uuid:event_id>/register/', views.register_event, name='register_event'),
    path('events/register/<slug:registration_link>/', views.register_event_by_link, name='register_event_by_link'),
    path('events/<uuid:event_id>/update-notifications/', views.update_notification_preferences, name='update_notification_preferences'),
    path('events/<uuid:event_id>/share-email/', views.share_event_email, name='share_event_email'),
    path('events/<uuid:event_id>/submit-feedback/', views.submit_feedback, name='submit_feedback'),
    path('events/<uuid:event_id>/export-csv/', views.export_registrations_csv, name='export_registrations_csv'),
    path('events/<uuid:event_id>/email-attendees/', views.email_attendees, name='email_attendees'),
    path('sponsors/events/', views.sponsor_events, name='sponsor_events'),
    path('sponsors/profile/', views.sponsor_profile, name='sponsor_profile'),
    path('sponsors/analytics/', views.sponsor_analytics, name='sponsor_analytics'),
    path('sponsors/analytics/<uuid:event_id>/', views.sponsor_event_analytics, name='sponsor_event_analytics'),
    path('sponsors/materials/', views.sponsor_materials, name='sponsor_materials'),
    path('sponsors/materials/<uuid:event_id>/', views.sponsor_event_materials, name='sponsor_event_materials'),
    path('sponsors/settings/', views.sponsor_settings, name='sponsor_settings'),

    # Admin Dashboard URLs
    path('admin/dashboard/', admin_views.admin_dashboard, name='admin_dashboard'),
    path('admin/users/', admin_views.admin_users, name='admin_users'),
    path('admin/users/add/', admin_views.add_user, name='add_user'),
    path('admin/users/add-admin/', admin_views.add_admin, name='add_admin'),
    path('admin/users/import/', admin_views.import_users, name='import_users'),
    path('admin/users/export/', admin_views.export_users, name='export_users'),
    path('admin/events/', admin_views.admin_events, name='admin_events'),
    path('admin/speakers/', admin_views.admin_speakers, name='admin_speakers'),
    path('admin/revenue/', admin_views.admin_revenue, name='admin_revenue'),
    path('admin/checkins/', admin_views.admin_checkins, name='admin_checkins'),
    path('admin/feedback/', admin_views.admin_feedback, name='admin_feedback'),
    path('admin/site-settings/', admin_views.admin_site_settings, name='admin_site_settings'),
    path('admin/blog/', admin_views.admin_blog, name='admin_blog'),
    path('admin/contact-messages/', admin_views.admin_contact_messages, name='admin_contact_messages'),
    path('reports/download/<str:report_type>/', views.download_report, name='download_report'),
    path('recent/', views.recent_events, name='recent_events'),
    path('browse/', views.browse_events, name='browse_events'),
    path('events/<uuid:event_id>/cancel/', views.cancel_registration, name='cancel_registration'),
]